[tools]
python = "3.12"

[tasks.default]
description = "Show available tasks"
run = "mise tasks"

[tasks.install-python]
description = "Install the Python version of gst for development"
run = """
cd python
uv sync
echo "✅ Python gst environment synchronized!"
echo "You can now use: mise run gst"
echo "Or directly: cd python && uv run gst"
"""

[tasks.install-python-pipx]
description = "Install the Python version of gst globally using pipx"
run = """
pipx install python/
echo "✅ Python gst installed with pipx!"
echo "You can now use: gst"
"""

[tasks.install-python-pipx-remote]
description = "Install the Python version of gst from GitHub using pipx"
run = """
pipx install git+https://github.com/delorenj/gst.git#subdirectory=python
echo "✅ Python gst installed with pipx from GitHub!"
echo "You can now use: gst"
"""

[tasks.install-python-global]
description = "Install the Python version of gst globally using uv tool"
run = """
cd python
uv tool install .
echo "✅ Python gst installed globally!"
echo "You can now use: gst"
"""

[tasks.run-python-gst]
description = "Run the Python version of gst"
run = """
cd python
uv run python gst.py "$@"
"""

[tasks.python-gst]
alias = "gst"
description = "Run the Python version of gst (alias)"
run = """
cd python
uv run python gst.py "$@"
"""